/**
 * lib/email.js — Shared server-side helpers for the newsletter / email-capture flow.
 *
 * WHAT THIS FILE IS
 * -----------------
 * A dependency-free utility module imported by the Cloudflare Pages Functions
 * (`functions/api/*`) that power double opt-in email subscription:
 *   - subscribe   → validate + honeypot + Turnstile, upsert a `pending` row, send confirm mail
 *   - confirm     → flip `pending` → `confirmed` by matching the emailed token
 *   - unsubscribe → flip a row to `unsubscribed` by matching its unsubscribe token
 * This module holds ONLY the shared primitives (validation, HTTP helpers,
 * Turnstile verification, Supabase data access, Resend mail send). The per-route
 * orchestration lives in the individual Functions that import from here.
 *
 * SINGLE RESPONSIBILITY
 * ---------------------
 * Be the trusted server-side boundary for subscriber data and outbound mail:
 * every read/write to the `subscribers` table and every transactional email
 * funnels through these functions, so validation and auth assumptions live in
 * exactly one place.
 *
 * WHERE IT FITS IN THE ARCHITECTURE
 * ---------------------------------
 * Browser (subscribe form) → Cloudflare Pages Function → (this module) →
 *   • Cloudflare Turnstile siteverify   (bot check)
 *   • Supabase PostgREST                (Postgres data, guarded by RLS)
 *   • Resend                            (transactional confirmation email)
 * Runs in the Cloudflare Workers runtime, so it relies only on Workers-native
 * globals (`fetch`, `Response`, `URLSearchParams`, `crypto`) — no Node built-ins,
 * no npm dependencies. That keeps the Function bundle tiny and cold-start fast.
 *
 * DEPENDS ON (runtime env bindings — never hard-coded, injected per request):
 *   - TURNSTILE_SECRET_KEY        (optional; absence disables bot check — see verifyTurnstile)
 *   - SUPABASE_URL                (PostgREST base URL)
 *   - SUPABASE_SERVICE_ROLE_KEY   (SECRET — bypasses RLS; see security note below)
 *   - RESEND_API_KEY              (SECRET — Resend transactional API)
 *   - SITE_URL, EMAIL_FROM        (optional; have safe production defaults)
 *
 * DEPENDED ON BY:
 *   - functions/api/subscribe (isValidEmail, normalizeEmail, verifyTurnstile,
 *       getByEmail, insertPending, setPendingToken, sendConfirmationEmail, jsonResponse)
 *   - functions/api/confirm     (confirmByToken, redirect)
 *   - functions/api/unsubscribe (unsubscribeByToken, isUuid, redirect/jsonResponse)
 *   (exact import set may vary; these are the intended consumers.)
 *
 * SECURITY ASSUMPTIONS / GOTCHAS
 * ------------------------------
 *   1. SERVICE-ROLE KEY BYPASSES RLS. The `subscribers` table has Row-Level
 *      Security ENABLED with NO policies, meaning the anon/public key can read
 *      nothing. The service-role key used here bypasses RLS entirely, so this
 *      module is the ONLY code path allowed to touch the table. Consequence:
 *      this key must NEVER be exposed to the browser or logged. All validation
 *      and gating must happen here — the database will not second-guess us.
 *   2. TOKENS ARE THE ONLY SECRET. Confirm/unsubscribe are authenticated purely
 *      by an unguessable token in the URL (generated by the caller, not here).
 *      There is no session. Token comparison happens in Postgres via an equality
 *      filter, so tokens must be high-entropy and treated as bearer secrets.
 *   3. TURNSTILE IS FAIL-OPEN WHEN UNCONFIGURED (see verifyTurnstile) — an
 *      intentional trade-off so the form works before keys are provisioned.
 *   4. Every value interpolated into a PostgREST URL is passed through
 *      encodeURIComponent to prevent filter/query injection.
 */

// Shared helpers for the email-capture Cloudflare Pages Functions.
// No external dependencies — uses the Workers-native fetch/crypto.

/**
 * Cheap, defensive email syntax check (NOT full RFC 5322 — deliberately).
 * WHY: we only need to reject obviously-malformed input before spending a
 * Supabase round-trip and a Resend send; true validity is proven by the user
 * actually clicking the confirmation link (double opt-in).
 * - Rejects non-strings so callers can pass untrusted JSON straight in.
 * - 254-char cap is the SMTP maximum length for an email address.
 * - Regex requires exactly one "@" with non-space text on both sides and a dot
 *   in the domain. Intentionally loose to avoid rejecting valid exotic addresses.
 */
export function isValidEmail(email) {
  if (typeof email !== 'string') return false;
  const e = email.trim();
  return e.length <= 254 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
}

/**
 * Canonicalize an address for storage/lookup so "  Foo@Bar.com " and
 * "foo@bar.com" collide on the table's UNIQUE(email) constraint and can never
 * create two rows for the same human. WHY lowercase: mailbox case *can* be
 * significant per RFC, but in practice no real provider treats it that way, and
 * de-duplication matters more than pedantic correctness here.
 * NOTE: String(email) coerces defensively — normalize is sometimes called on
 * values that isValidEmail hasn't vetted.
 */
export function normalizeEmail(email) {
  return String(email).trim().toLowerCase();
}

/**
 * Strict RFC-4122 UUID shape check (case-insensitive). Used to sanity-check
 * caller-supplied row ids before they are spliced into a PostgREST filter,
 * so a malformed/hostile id is rejected in-process rather than sent to the DB.
 */
export function isUuid(s) {
  return (
    typeof s === 'string' &&
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s)
  );
}

/**
 * Build a JSON `Response` for the Workers runtime. Centralized so every API
 * route returns the same content-type (with explicit charset) and so status
 * codes are set consistently. Used for XHR/fetch responses to the front-end.
 */
export function jsonResponse(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8' },
  });
}

/**
 * Build a 302 redirect. Used by confirm/unsubscribe routes, which are opened by
 * a human clicking a link in an email (a top-level browser navigation, not a
 * fetch) — so they must respond with a redirect to a friendly result page
 * rather than a JSON blob.
 * SECURITY NOTE: `location` is always a first-party path/URL chosen by the
 * calling Function, never derived from user input, so this is not an open-redirect.
 */
export function redirect(location) {
  return new Response(null, { status: 302, headers: { location } });
}

// --- Cloudflare Turnstile ----------------------------------------------------
// Opt-in: when TURNSTILE_SECRET_KEY is unset, verification is skipped so the
// form keeps working until keys are configured. Once set, a valid token is required.
/**
 * Server-side verification of a Cloudflare Turnstile bot-check token.
 * @returns {Promise<boolean>} true = allow the request to proceed.
 *
 * FAIL-OPEN (unconfigured): if no secret key is set we return true. WHY: this is
 *   a deliberate bootstrapping trade-off so the subscribe form is usable before
 *   Turnstile keys are provisioned. Once TURNSTILE_SECRET_KEY exists, a token is
 *   mandatory. GOTCHA: never remove the key in prod expecting protection to stay.
 * FAIL-CLOSED (configured): a missing token, a non-OK HTTP response from the
 *   siteverify endpoint, or `success !== true` all return false — any doubt is
 *   treated as "not human". We do not retry; a transient siteverify blip simply
 *   asks the user to try again, which is safer than letting bots through.
 * The token is single-use and validated by Cloudflare; `remoteip` is an optional
 * extra signal (only sent when the caller could determine the client IP).
 */
export async function verifyTurnstile(env, token, ip) {
  if (!env.TURNSTILE_SECRET_KEY) return true;
  if (!token) return false;
  const form = new URLSearchParams();
  form.set('secret', env.TURNSTILE_SECRET_KEY);
  form.set('response', token);
  if (ip) form.set('remoteip', ip);
  const res = await fetch(
    'https://challenges.cloudflare.com/turnstile/v0/siteverify',
    { method: 'POST', body: form }
  );
  if (!res.ok) return false;
  const data = await res.json();
  // Strict === true: the API returns a boolean, but we refuse to trust any
  // truthy-but-not-true shape (defense against unexpected response formats).
  return data.success === true;
}

// --- Supabase (PostgREST) ----------------------------------------------------
// The service-role key bypasses RLS; the table has RLS enabled with no policies,
// so ONLY this server-side function can read/write it.

/**
 * Standard headers for every PostgREST call. Sends the SERVICE-ROLE key in both
 * `apikey` (Supabase gateway auth) and `authorization: Bearer` (PostgREST role
 * selection). This role bypasses RLS — see the file-header security note. Kept
 * private (not exported) so the privileged key never leaks into other modules.
 */
function sbHeaders(env) {
  return {
    apikey: env.SUPABASE_SERVICE_ROLE_KEY,
    authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
    'content-type': 'application/json',
  };
}

/**
 * Look up a single subscriber by exact email. Returns the row (id/status/
 * last_email_at) or null if none. Used by the subscribe route to decide between
 * inserting a new pending row vs. re-issuing a token to an existing row, and to
 * enforce rate-limiting via last_email_at.
 * `encodeURIComponent(email)` guards the PostgREST `eq.` filter against injection.
 * A non-2xx response throws with the body text so failures surface in logs
 * rather than being silently swallowed.
 */
export async function getByEmail(env, email) {
  const url = `${env.SUPABASE_URL}/rest/v1/subscribers?email=eq.${encodeURIComponent(
    email
  )}&select=id,status,last_email_at`;
  const res = await fetch(url, { headers: sbHeaders(env) });
  if (!res.ok) throw new Error(`supabase select ${res.status}: ${await res.text()}`);
  const rows = await res.json();
  return rows[0] ?? null;
}

/**
 * Insert a brand-new subscriber in the `pending` state with its confirmation
 * token. `prefer: return=minimal` tells PostgREST not to echo the row back
 * (we don't need it — saves bandwidth). `last_email_at` seeds the rate-limit clock.
 *
 * IDEMPOTENCY / RACE HANDLING: a 409 means the UNIQUE(email) constraint fired
 * because a concurrent request (double-click, retry) inserted the same address
 * first. We swallow it as success — the row exists in the intended state, which
 * is all the caller cares about. Any other non-OK status throws with the body.
 */
export async function insertPending(env, email, confirmToken, nowIso) {
  const res = await fetch(`${env.SUPABASE_URL}/rest/v1/subscribers`, {
    method: 'POST',
    headers: { ...sbHeaders(env), prefer: 'return=minimal' },
    body: JSON.stringify([
      { email, status: 'pending', confirm_token: confirmToken, last_email_at: nowIso },
    ]),
  });
  // 409 = unique-email race (a concurrent request inserted first). Treat as fine.
  if (res.status === 409) return;
  if (!res.ok) throw new Error(`supabase insert ${res.status}: ${await res.text()}`);
}

/**
 * Re-arm an EXISTING subscriber row for (re)confirmation: reset it to `pending`,
 * write a freshly generated token, and stamp last_email_at. Called by the
 * subscribe route when getByEmail found a row (e.g. someone who previously
 * unsubscribed or never confirmed asks again). Rotating the token invalidates
 * any older confirmation link. Targeted by primary-key `id`, which the caller
 * should have validated via isUuid; encodeURIComponent still guards the filter.
 */
export async function setPendingToken(env, id, confirmToken, nowIso) {
  const res = await fetch(
    `${env.SUPABASE_URL}/rest/v1/subscribers?id=eq.${encodeURIComponent(id)}`,
    {
      method: 'PATCH',
      headers: { ...sbHeaders(env), prefer: 'return=minimal' },
      body: JSON.stringify({
        status: 'pending',
        confirm_token: confirmToken,
        last_email_at: nowIso,
      }),
    }
  );
  if (!res.ok) throw new Error(`supabase patch ${res.status}: ${await res.text()}`);
}

/**
 * Complete double opt-in: match a row by its confirmation token and flip it to
 * `confirmed`, stamping confirmed_at. `prefer: return=representation` makes
 * PostgREST return the affected rows so we can tell caller whether a match
 * occurred: returns true if >=1 row updated, false if the token was unknown.
 *
 * The equality filter on confirm_token IS the authentication for this endpoint
 * — there is no session. The token must therefore be unguessable (bearer secret).
 * See the inline note below on why the token is intentionally NOT cleared.
 */
export async function confirmByToken(env, token) {
  // Idempotent by design: we do NOT clear confirm_token, so a re-click — or a
  // mail-security scanner prefetching the link followed by the human's real
  // click — both still match and land on success instead of a false error.
  const res = await fetch(
    `${env.SUPABASE_URL}/rest/v1/subscribers?confirm_token=eq.${encodeURIComponent(token)}`,
    {
      method: 'PATCH',
      headers: { ...sbHeaders(env), prefer: 'return=representation' },
      body: JSON.stringify({ status: 'confirmed', confirmed_at: new Date().toISOString() }),
    }
  );
  if (!res.ok) throw new Error(`supabase confirm ${res.status}`);
  const rows = await res.json();
  return rows.length > 0;
}

/**
 * One-click unsubscribe: match a row by its (separate, long-lived)
 * unsubscribe_token and set status to `unsubscribed`. Returns true if a row
 * matched, false otherwise. Uses a DISTINCT token from confirm_token so the
 * unsubscribe link embedded in every sent email cannot be used to confirm, and
 * survives across the subscribe→confirm lifecycle. As with confirmByToken, the
 * token match is the sole authenticator, so it must be unguessable.
 */
export async function unsubscribeByToken(env, token) {
  const res = await fetch(
    `${env.SUPABASE_URL}/rest/v1/subscribers?unsubscribe_token=eq.${encodeURIComponent(token)}`,
    {
      method: 'PATCH',
      headers: { ...sbHeaders(env), prefer: 'return=representation' },
      body: JSON.stringify({ status: 'unsubscribed' }),
    }
  );
  if (!res.ok) throw new Error(`supabase unsub ${res.status}`);
  const rows = await res.json();
  return rows.length > 0;
}

// --- Resend ------------------------------------------------------------------

/**
 * Send the double opt-in confirmation email via Resend's transactional API.
 * SITE_URL and EMAIL_FROM fall back to production defaults so the function works
 * even if those optional bindings are unset. The confirmation link points at the
 * first-party /api/confirm route carrying the token, which confirmByToken later
 * matches. Throws (with response body) on any non-OK status so the subscribe
 * route can surface a failed send rather than pretending the email went out.
 *
 * GOTCHA: `confirmToken` is interpolated raw into the URL query. It is generated
 * server-side (URL-safe, high-entropy) and never user-supplied, so it needs no
 * escaping here; do not repurpose this to embed untrusted values.
 */
export async function sendConfirmationEmail(env, email, confirmToken) {
  const site = env.SITE_URL || 'https://areyoustillreading.dev';
  const from = env.EMAIL_FROM || 'areyoustillreading <hello@areyoustillreading.dev>';
  const confirmUrl = `${site}/api/confirm?token=${confirmToken}`;
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      authorization: `Bearer ${env.RESEND_API_KEY}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      from,
      to: [email],
      subject: 'Confirm your subscription',
      html: `<p>Thanks for subscribing to <strong>areyoustillreading</strong>.</p>
<p><a href="${confirmUrl}">Click here to confirm your subscription</a>.</p>
<p>If you didn't request this, you can safely ignore this email.</p>`,
    }),
  });
  if (!res.ok) throw new Error(`resend ${res.status}: ${await res.text()}`);
}
